title: Cucaracha alibianada
description: "Un eficiente y loco probrama de personal \U0001F6C2\U0001F39B️"
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
